In [74]:
!pip list

Package                           Version
--------------------------------- ------------------
absl-py                           2.1.0
aext-assistant                    4.0.15
aext-assistant-server             4.0.15
aext-core                         4.0.15
aext-core-server                  4.0.15
aext-panels                       4.0.15
aext-panels-server                4.0.15
aext-share-notebook               4.0.15
aext-share-notebook-server        4.0.15
aext-shared                       4.0.15
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.6
aiohttp                           3.11.12
aioitertools                      0.7.1
aiosignal                         1.3.2
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.3
anaconda-pr

In [75]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [76]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable


#### Load library

In [78]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [79]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [80]:
a = tf.constant(3e-38)
type(a), a.shape, a.dtype

(tensorflow.python.framework.ops.EagerTensor, TensorShape([]), tf.float32)

In [81]:
a = tf.constant([3, 2, 3.])
type(a), a.shape, a.dtype

(tensorflow.python.framework.ops.EagerTensor, TensorShape([3]), tf.float32)

In [82]:
a = tf.Variable([[3, 2., 3], [3, 2, 3]])
type(a), a.shape, a.dtype

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 TensorShape([2, 3]),
 tf.float32)

In [83]:
a = tf.Variable([[[[[3, 2, 3], [3, 2, 3]],]]])
type(a), a.shape, a.dtype

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 TensorShape([1, 1, 1, 2, 3]),
 tf.int32)

In [84]:
a = tf.Variable([[[3, 2, 3], [3, 2, 3]],[[3, 2, 3], [3, 2, 3]]])
type(a), a.shape, a.dtype

(tensorflow.python.ops.resource_variable_ops.ResourceVariable,
 TensorShape([2, 2, 3]),
 tf.int32)

#### Gradient tape

In [86]:
a = tf.constant([2.])
x = tf.Variable([3.,4])
y = 2*x + a

In [87]:
y.shape, y.dtype, y.numpy()

(TensorShape([2]), tf.float32, array([ 8., 10.], dtype=float32))

In [88]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = 2*x**1 + a

In [89]:
dy_dx = tape.gradient(y, x).numpy()
dy_dx

array([2., 2.], dtype=float32)

In [90]:
a = tf.constant([2.])
w1 = tf.Variable([3.,])
w2 = tf.Variable([1.,])

with tf.GradientTape(persistent=True) as tape:
    tape.watch(w1)
    tape.watch(w2)
    
    y = 2*w1**2 + w2**3 + a

In [91]:
dy_dw1, dy_dw2 = tape.gradient(y, [w1, w2])
dy_dw1.numpy(), dy_dw2.numpy()

(array([12.], dtype=float32), array([3.], dtype=float32))

In [92]:
a = tf.constant([2.])
W = tf.Variable([3., 2.])

with tf.GradientTape(persistent=True) as tape:
    tape.watch(W)
    
    y = 2*W[0]**2 + W[1]**3 + a

In [93]:
tape.gradient(y, W)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 12.], dtype=float32)>